[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/excel-upload"
  to = "/.netlify/functions/excel-upload"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/feishu-api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 